# Generated by Django 5.1.6 on 2025-02-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeimb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='imb',
        ),
    ]
