# Generated by Django 5.1.6 on 2025-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeimb', '0003_rename_address_imb_streetaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='imb',
            name='dropboxid',
            field=models.IntegerField(default=0),
        ),
    ]
