# Generated by Django 5.1.6 on 2025-02-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeimb', '0005_imb_code39'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imb',
            name='dropboxid',
        ),
    ]
