# Generated by Django 5.1.6 on 2025-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeimb', '0006_remove_imb_dropboxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imb',
            name='dropboxid',
            field=models.IntegerField(default=0),
        ),
    ]
