# Generated by Django 5.1.6 on 2025-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeimb', '0007_imb_dropboxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imb',
            name='imb',
            field=models.CharField(default=0, max_length=66),
            preserve_default=False,
        ),
    ]
