prod: false 

server: 
  host: "192.168.0.40"
  port: 8000
  live_feed_port: 5005

dropbox: 
  id: 1 
  address: ""

scanners:  
  scanner1: 
    vendor_id: 0x0c2e
    product_id: 0x0aaf
  # scanner2: 
  #   vendor_id: 0x0c2e
  #   product_id: 0x0aaf



