prod: false 

server: 
  host: "13.59.39.53"
  port: 8000
  live_feed_port: 5005

dropbox: 
  id: 2 
  address: ""

scanners:  
  scanner1: 
    vendor_id: 0x0c2e
    product_id: 0x0aaf
  # scanner2: 
  #   vendor_id: 0x0c2e
  #   product_id: 0x0aaf



