# Generated by Django 5.1.6 on 2025-03-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropboxid', models.IntegerField(default=1)),
                ('imb', models.CharField(max_length=66)),
                ('code39', models.CharField(max_length=44)),
                ('date', models.CharField(max_length=255)),
                ('streetaddress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
