# Generated by Django 5.1.6 on 2025-04-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dropbox',
            fields=[
                ('dropboxid', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=66)),
                ('coordinates', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='EnvelopeScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imb', models.CharField(blank=True, max_length=66, null=True)),
                ('code39', models.CharField(max_length=44, unique=True)),
                ('date', models.CharField(max_length=255)),
                ('streetaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('dropboxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='dashboard.dropbox')),
            ],
        ),
    ]
