# Generated by Django 5.1.6 on 2025-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopescan',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envelopescan',
            name='imb',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='envelopescan',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envelopescan',
            name='streetaddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envelopescan',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
