# Generated by Django 5.1.6 on 2025-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_envelopescan_city_alter_envelopescan_imb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopescan',
            name='code39',
            field=models.CharField(max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='envelopescan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
